Absences and reservations features
zorzalo3/zorza pull request #59
Opened 2023-07-01 18:51 UTC by Igifigi

This PR brings some new features and fixes bugs by removing the display of reservations. Main features:
- form for adding absences (#1),
- ability to delete reservations and absences from the absence management view, as like with substitutions,
- fix the display of absences,
- removed the display of reservations in room timetable and rooms view due to poor and bug-prone implementation.

2023-07-01 19:28 UTC, opti0 commented
Closes #1

2023-07-04 10:19 UTC, opti0 requested changes
Some changes in translations required.

2023-07-04 10:19 UTC, opti0 commented on locale/pl/LC_MESSAGES/django.po
> +msgstr "Dodawanie rezerwacji"
`msgstr "Dodawanie nieobecności grup"`

2023-07-04 10:19 UTC, opti0 commented on locale/pl/LC_MESSAGES/django.po
> +msgstr "Okres początkowa"
"Początek nieobecności" albo "Lekcja początkowa"

2023-07-04 10:19 UTC, opti0 commented on locale/pl/LC_MESSAGES/django.po
> +msgstr "Okres końcowy"
"Koniec nieobecności" albo "Lekcja końcowa"

2023-07-04 10:19 UTC, opti0 commented on locale/pl/LC_MESSAGES/django.po
> +msgstr "Proszę wprowadzić poprawny początkowy i końcowy okres."
Wprowadź poprawną lekcję rozpoczęcia i zakończenia nieobecności.

2023-07-04 15:46 UTC, Igifigi commented
Everything fixed.

2023-07-07 07:38 UTC, opti0 approved these changes

2023-07-07 07:39 UTC, merged